package org.notesapp.data.model

/**
 * Domain model representing a Note.
 * @param id Autogenerated identifier.
 * @param title Note title (required, 1..120 chars).
 * @param body HTML body string (required, validated separately).
 * @param createdDateMillis Unix epoch millis of the created date (local date at midnight OK).
 */
data class Note(
  val id: Long,
  val title: String,
  val body: String,
  val createdDateMillis: Long,
)
